apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: {{.Values.app.Namespace}}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - http:
      paths:
      - path: /replacement
        pathType: Exact
        backend:
          service:
            name: replacement-svc
            port:
              number: 80
      - path: /
        pathType: Exact
        backend:
          service:
            name: replacement-svc
            port:
              number: 80
    host: replacement-svc.{{.Values.app.Namespace}}
        