apiVersion: v1
kind: Service
metadata:
  name: replacement-svc
  namespace: {{.Values.app.Namespace}}
spec:
  selector:
    app: replacement
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort